### ISSUE TITLE
css样式更改

### ISSUE THREAD

**Issue by Apleax** [wyf9/sleepy#7]
页面宽度过于小的时候.card会被挤压溢出,可能会导致内容在一些移动设备上缺失
建议修改style.css
```css
body, html {
    margin: 0;
    padding: 0;
    height: 100%;
    ~overflow: hidden~   //移除overflow: hidden
}
```

添加
```css
@media (max-width: 675px) {
    body {
        display: unset;
    }
}
```
